steps:
  - name: node:12.6.0
    entrypoint: yarn
    args: ["install"]
  - name: node:12.6.0
    entrypoint: yarn
    args: ["add", "firebase-tools"]
  - name: node:12.6.0
    entrypoint: npm
    args: ["build"]
  - name: "node:12.6.0"
    entrypoint: "./node_modules/.bin/firebase"
    args: ["deploy", "--project", "$PROJECT_ID", "--token", "$_TOKEN"]
